ALTER TABLE claims ADD COLUMN decl_pkg_dir  TEXT NOT NULL DEFAULT '';
ALTER TABLE claims ADD COLUMN decl_receiver TEXT NOT NULL DEFAULT '';
ALTER TABLE claims ADD COLUMN decl_name     TEXT NOT NULL DEFAULT '';
